on: [push]

jobs:
  newrelic:
    runs-on: ubuntu-latest
    name: New Relic
    steps:
      - name: Set Release Version from Tag
        run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF:10}

      - name: Create New Relic deployment marker
        uses: newrelic/deployment-marker-action@master
        with:
          apiKey: ${{ secrets.NEW_RELIC_API_KEY }}
          accountId: ${{ secrets.NEW_RELIC_ACCOUNT_ID }}
          applicationId: ${{ secrets.NEW_RELIC_APPLICATION_ID }}
          revision: "${{ env.RELEASE_VERSION }}"
          description: "This is the best deployment marker"
          changelog: "Things changed, here is the log. Super exciting."
















# jobs:
#   new_relic:
#     runs-on: ubuntu-latest
#     name: New Relic Deployment Marker GitHub Action
#     steps:
#       # - name: Checkout
#       #   uses: actions/checkout@v2

#       - name: Create deployment marker
#         uses: newrelic/deployment-marker-action@feat/test-the-action
#         with:
#           apiKey: ${{ secrets.NEW_RELIC_API_KEY }}
#           accountId: ${{ secrets.NEW_RELIC_ACCOUNT_ID }}
#           region: US
#           applicationId: ${{ secrets.NEW_RELIC_APPLICATION_ID }}
#           revision: 'sblue-newrelic-deployment-marker-action-${{ github.sha }}'
#           user: '${{ github.actor }}'
