name: Release

on:
  - release

jobs:
  basic_test:
    runs-on: ubuntu-latest
    name: Deployment marker example
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Release Version from Tag
        run: echo "RELEASE_VERSION=${{ GITHUB_REF:10 }}" >> $GITHUB_ENV

      - name: Test deployment marker
        uses: ./
        with:
          apiKey: ${{ secrets.NEW_RELIC_API_KEY }}
          accountId: ${{ secrets.NEW_RELIC_ACCOUNT_ID }}
          applicationId: ${{ secrets.NEW_RELIC_APPLICATION_ID }}
          revision: "${{ github.repository }}:${{ env.RELEASE_VERSION }}"
